apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sample-external-secret
  namespace: external-secrets
spec:
  refreshInterval: "10s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-clustersecretstore
  target:
    name: eso-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: kv/cred
        property: username
    - secretKey: password
      remoteRef:
        key: kv/cred
        property: password
